# Generated by Django 6.1.1 on 2026-10-04 09:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='RAKTCH TECHNOLOGY & SOFTWARE', max_length=255)),
                ('tagline', models.CharField(blank=True, default='TECHNOLOGY & SOFTWARE', max_length=255)),
                ('address', models.TextField(default='Sector 6, Road 5, House 20, 7th floor, Uttara, Dhaka -1230, Bangladesh')),
                ('website', models.CharField(blank=True, default='www.raktch.com', max_length=255)),
                ('email', models.CharField(blank=True, default='raktchme@gmail.com, support@raktch.com', max_length=255)),
                ('phone', models.CharField(blank=True, default='+8801581677077', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('authorization_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Software Monthly Bill', max_length=100)),
                ('title_pattern', models.CharField(default='{service_name} Monthly Bill ({month_year})', help_text='Supported placeholders: {service_name}, {month_year}, {client_name}', max_length=255)),
                ('invoice_number_prefix', models.CharField(default='INV-', max_length=20)),
                ('nb_text', models.TextField(default='[N.B Please send the bill to]')),
                ('authorization_label', models.CharField(default='Authorization', max_length=100)),
                ('received_by_label', models.CharField(default='Received by', max_length=100)),
                ('is_default', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('default_tech_specification', models.TextField(default='Hosting & Maintenance Bill')),
                ('default_price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('ONE_TIME', 'One Time')], default='MONTHLY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Islami Bank PLC', max_length=255)),
                ('account_name', models.CharField(default='RAKTCH TECHNOLOGY AND SOFTWARE', max_length=255)),
                ('account_number', models.CharField(default='20502180100311104', max_length=100)),
                ('branch_name', models.CharField(default='Haji Camp, Ashkona, Dakkhin khan', max_length=255)),
                ('routing_number', models.CharField(default='125261995', max_length=100)),
                ('is_default', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='billing.company')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(help_text='e.g. Supershop Software Monthly Bill (April-2026)', max_length=255)),
                ('billing_month', models.CharField(blank=True, help_text='e.g. April-2026', max_length=50)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_tagline', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('company_website', models.CharField(blank=True, max_length=255)),
                ('company_email', models.CharField(blank=True, max_length=255)),
                ('company_phone', models.CharField(blank=True, max_length=100)),
                ('company_logo_snapshot', models.ImageField(blank=True, null=True, upload_to='invoices/logos/')),
                ('company_signature_snapshot', models.ImageField(blank=True, null=True, upload_to='invoices/signatures/')),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_contact_person', models.CharField(blank=True, max_length=150)),
                ('client_address', models.TextField(blank=True)),
                ('client_phone', models.CharField(blank=True, max_length=50)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=255)),
                ('routing_number', models.CharField(blank=True, max_length=100)),
                ('nb_text', models.TextField(blank=True, default='[N.B Please send the bill to]')),
                ('currency_symbol', models.CharField(default='Tk', max_length=10)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('authorization_label', models.CharField(default='Authorization', max_length=100)),
                ('received_by_label', models.CharField(default='Received by', max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='invoices/qrcodes/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.bankaccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.company')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoicetemplate')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.PositiveIntegerField(default=1)),
                ('item_name', models.CharField(max_length=255)),
                ('technical_specification', models.TextField(blank=True, default='Hosting & Maintenance Bill')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.service')),
            ],
            options={
                'ordering': ['sl', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(default='Tk', max_length=10)),
                ('currency_code', models.CharField(default='BDT', max_length=10)),
                ('default_nb_text', models.TextField(default='[N.B Please send the bill to]')),
                ('invoice_footer_note', models.CharField(blank=True, default='www.raktch.com', max_length=255)),
                ('default_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.bankaccount')),
                ('default_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.company')),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='ClientServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, help_text="Custom name for this client's bill, e.g. 'Supershop Software'", max_length=255)),
                ('custom_tech_specification', models.TextField(blank=True, help_text="Custom specification, e.g. 'Hosting & Maintenance Bill'")),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_services', to='billing.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_pricings', to='billing.service')),
            ],
            options={
                'unique_together': {('client', 'service')},
            },
        ),
    ]
