# Generated by Django 6.1.1 on 2026-10-04 09:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=50, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Advance payment received', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT rate percentage, e.g. 5.00 for 5%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='payable - advance - paid', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of recorded payments', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='subtotal - discount + vat', max_digits=12),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ACCOUNTANT', 'Accountant'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
