# Generated by Django 6.1.1 on 2026-10-06 07:34

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_loginattempt_username_alter_payment_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('trigger', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], default='AUTO', max_length=20)),
                ('target_period', models.CharField(blank=True, help_text='e.g. 2026-05 or May-2026', max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-run_time'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_period',
            field=models.CharField(blank=True, db_index=True, help_text="Standardized period key e.g. '2026-05' or 'May-2026'", max_length=50),
        ),
        migrations.AddField(
            model_name='settings',
            name='auto_billing_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of month to run auto-generation (1-31)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='auto_billing_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic recurring bill generation'),
        ),
        migrations.AddField(
            model_name='settings',
            name='auto_billing_time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Time of day to run auto-generation'),
        ),
        migrations.AddField(
            model_name='settings',
            name='auto_billing_timezone',
            field=models.CharField(default='Asia/Dhaka', help_text='Timezone for scheduler', max_length=50),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, help_text="Custom name for bill item, e.g. 'Supershop Software'", max_length=255)),
                ('custom_tech_specification', models.TextField(blank=True, help_text='Custom specification for bill item')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('auto_status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued')], default='ISSUED', help_text='Default status for auto-generated invoices (DRAFT needs review, ISSUED is final)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='billing.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.subscription'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('subscription__isnull', False)), fields=('subscription', 'billing_period'), name='unique_invoice_per_subscription_period'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('client', 'service')},
        ),
    ]
