# Generated by Django 6.1.1 on 2026-10-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='scheduler_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent scheduler execution/heartbeat', null=True),
        ),
    ]
